apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- promotion_service.yaml
images:
- name: controller
  newName: ghcr.io/weaveworks/pipeline-controller
  newTag: v0.0.30-5-g75c5b9f-dirty
