apiVersion: v1
kind: Service
metadata:
  name: pipeline-promotion
  labels:
    control-plane: controller
spec:
  type: ClusterIP
  selector:
    app: pipeline-controller
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: promotion
