controller:
  manager:
    image:
      repository: ghcr.io/weaveworks/pipeline-controller
      tag: v0.0.2-2-ge46ab5f-dirty
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
promotion:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: promotion
  type: ClusterIP
