name: CI for Helm chart

on:
  pull_request:
    paths:
      - "charts/**"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required"'
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required"'
  verify-tidy:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required"'
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required"'

  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.10.1
      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: "3.10"
          check-latest: true
      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1
      - name: Create k8s kind cluster
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
      - name: Lint and install
        run: make lint-and-install-chart
