name: CI for Helm chart

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1
      - name: Lint
        run: make lint-chart
