name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "charts/**" # https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
  pull_request_target:
    types:
      - closed

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
        cache: true
    - name: Prepare
      run: |
        echo "machine github.com login ${{ github.actor }} password ${{ secrets.BUILD_BOT_TOKEN }}" > ~/.netrc
    - name: Lint
      run: make lint

  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No lint for Helm chart required"'

  verify-tidy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
        cache: true
    - name: Prepare
      run: |
        echo "machine github.com login ${{ github.actor }} password ${{ secrets.BUILD_BOT_TOKEN }}" > ~/.netrc
    - name: Verify
      run: make verify-tidy

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
        cache: true
    - name: Prepare
      run: |
        echo "machine github.com login ${{ github.actor }} password ${{ secrets.BUILD_BOT_TOKEN }}" > ~/.netrc
    - name: Test
      run: make test

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
        cache: true
    - name: Prepare # .netrc is used by docker-build, ~/.netrc is used by go test
      run: echo "machine github.com login ${{ github.actor }} password ${{ secrets.BUILD_BOT_TOKEN }}" | tee ~/.netrc .netrc
    - name: Build
      run: make docker-build
    
  push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [lint, verify-tidy, test, build]
    permissions:
      contents: read # for actions/checkout to fetch code
      packages: write # needed for ghcr access
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
        cache: true
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Prepare # .netrc is used by docker-build, ~/.netrc is used by go test
      run: echo "machine github.com login ${{ github.actor }} password ${{ secrets.BUILD_BOT_TOKEN }}" | tee ~/.netrc .netrc
    - name: Push to GitHub Container Registry
      run: make docker-push # defaults to ghcr.io
    - name: Push to DockerHub
      run: IMG_REGISTRY=docker.io make docker-push
