name: e2e

on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.0
    - name: Setup
      uses: actions/setup-go@v4.0.0
      with:
        go-version: 1.20.x
    - name: Prepare
      run: |
        echo "machine github.com login ${{ github.actor }} password ${{ secrets.BUILD_BOT_TOKEN }}" > ~/.netrc 
    - name: Run E2E tests
      run: make e2e