name: Release chart

on:
  push:
    branches:
      - "main"
    paths:
      - "charts/**"

jobs:
  lint-chart:
    uses: ./.github/workflows/ci-chart.yaml
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Helm chart to GitHub Container Registry
        run: make helm-release
