name: Release chart

on:
  push:
    branches:
      - "main"
    paths:
      - "charts/**"

jobs:
  lint-chart:
    uses: ./.github/workflows/ci-chart.yaml
  release-chart:
    needs: [lint-chart]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Push Helm chart to GitHub Container Registry
        run: make helm-release
